title: Xetrapwn-Blog
description: "A Blog by enthusiast created for enthusiasts."
author:
  name: "Xetrapwn"
  email: "someone@somewebsite.somedomain"
  url: "https://xetrapwn.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Xetrapwn"
year : "2021"
