title: Xetrapwn-Blog
description: "A Blog by enthusiast created for enthusiasts."
author:
  name: "Xetrapwn"
  email: "someone@somewebsite.somedomain"
  url: "https://xetrapwn.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

title: Return-to-csu on ARM32
description: 
author:
  name: Xetrapwn
  email: [Your email address]
  url: "https://xetrapwn.github.io"

baseurl: "https://xetrapwn.github.io/return-to-csu_on_ARM32"

paginate: 3
owner: [Your name]
year: [Current Year]

# Custom variables
owner : "Xetrapwn"
year : "2021"
